// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_lkj2gaSsjx67gDAIuyyyin4kHyJk6hQ',
    appId: '1:603518155439:web:799dbf68018415c1e9b25a',
    messagingSenderId: '603518155439',
    projectId: 'doctor-app-c368f',
    authDomain: 'doctor-app-c368f.firebaseapp.com',
    storageBucket: 'doctor-app-c368f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0xpSd13gTXwhkD6YvJKig16sjZeJjGTI',
    appId: '1:603518155439:android:213ee39e656f1392e9b25a',
    messagingSenderId: '603518155439',
    projectId: 'doctor-app-c368f',
    storageBucket: 'doctor-app-c368f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAd5n-9wF24Ni8Lc-fxrZg4LpgNmViXBg8',
    appId: '1:603518155439:ios:d0aba8d21a2ae9bee9b25a',
    messagingSenderId: '603518155439',
    projectId: 'doctor-app-c368f',
    storageBucket: 'doctor-app-c368f.appspot.com',
    iosClientId: '603518155439-6sie4808udbtq8c84n2ki1mh1k471tnk.apps.googleusercontent.com',
    iosBundleId: 'com.example.ezhealthApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAd5n-9wF24Ni8Lc-fxrZg4LpgNmViXBg8',
    appId: '1:603518155439:ios:d0aba8d21a2ae9bee9b25a',
    messagingSenderId: '603518155439',
    projectId: 'doctor-app-c368f',
    storageBucket: 'doctor-app-c368f.appspot.com',
    iosClientId: '603518155439-6sie4808udbtq8c84n2ki1mh1k471tnk.apps.googleusercontent.com',
    iosBundleId: 'com.example.ezhealthApp',
  );
}
